<?php
/**
 * @file
 * Code for the toptaken module
 */

/**
 * Implements hook_views_api().
 */
function toptaken_views_api($module = NULL, $api = NULL) {
    return array("api" => "3.0");
  }
  
  /**
   * Implements hook_node_info().
   */
  function toptaken_node_info() {
    $items = array(
      'toptaak' => array(
        'name' => t('Toptaak'),
        'base' => 'node_content',
        'description' => '',
        'has_title' => '1',
        'title_label' => t('Title'),
        'help' => '',
      ),
    );
    drupal_alter('node_info', $items);
    return $items;
  }